<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"';
echo 'integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">';
echo '<link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.15.4/css/all.css'';
echo 'integrity='sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm' crossorigin='anonymous'>';
echo '<!-- <link rel="stylesheet" href="style.css">  -->';
echo '<link rel="stylesheet" href="style2.css">';
echo '<link rel="icon"';
echo 'href="https://cdn.shopify.com/s/files/1/0286/6557/7556/files/MY_BRIIICK_WALL_32x32.jpg?v=1574086590"';
echo 'type="image/x-icon" />';
echo '<title>The Largest Brick Slip And Brick Tile Supplier – My Brick Wall</title>';
echo '</head>';
echo '';
echo '<body>';
echo '<!-- navigation area starting -->';
echo '<nav>';
echo '<div class="nav-s1">';
echo '<div class="brand-details">';
echo '<div class="logo">';
echo '<a href="https://mybrickwall.co.uk/">';
echo '<img src="https://cdn.shopify.com/s/files/1/0286/6557/7556/files/logo_300x300@2x.png?v=1574872701"';
echo 'alt="logo">';
echo '</a>';
echo '</div>';
echo '<div class="offer-contact">';
echo '<div class="offer-img">';
echo '<img src="https://cdn.shopify.com/s/files/1/0286/6557/7556/t/20/assets/new-box.png?v=6807481583733761199"';
echo 'alt="offer">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="contact-links my-3">';
echo '<a href="https://mybrickwall.co.uk/pages/contact" class="cont-us">contact us</a>';
echo '<a href="https://mybrickwall.co.uk/account/login" class="log">login</a>';
echo '<a href="https://mybrickwall.co.uk/account/register" class="regi">register</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<nav class="navbar nan-menu-holder navbar-expand-lg py-3">';
echo '<div class="container-fluid p-0">';
echo '<button class="navbar-toggler nav-ham-btn" type="button" data-bs-toggle="collapse"';
echo 'data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false"';
echo 'aria-label="Toggle navigation">';
echo '<span class="ham-menu"><i class="fas fa-bars"></i></span>';
echo '</button>';
echo '<div class="collapse  navbar-collapse" id="navbarTogglerDemo01">';
echo '<ul class="navbar-nav nav-menus me-auto mb-2 mb-lg-0">';
echo '<li class="nav-item">';
echo '<a class="nav-link ms-0" aria-current="page"';
echo 'href="https://mybrickwall.co.uk/collections/brick-slips">BRICK SLIPS</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="https://mybrickwall.co.uk/collections/brick-tiles">BRICK TILES</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="https://mybrickwall.co.uk/collections/installation-aids"';
echo 'tabindex="-1" aria-disabled="true">ACCESSORIES</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" aria-current="page"';
echo 'href="https://mybrickwall.chameleonpower.com/#">VISUALIZER</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link"';
echo 'href="https://calendly.com/mybrickwall/showroom-visit?month=2022-03">SHOWROOM</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link"';
echo 'href="https://cdn.shopify.com/s/files/1/0286/6557/7556/files/HOW_TO_INSTALL_BRICK_SLIPS__INSTALLATION_GUIDE___2022___V01.pdf?v=1645447783"';
echo 'tabindex="-1" aria-disabled="true">INSTALLATION GUIDE</a>';
echo '</li>';
echo '</ul>';
echo '';
echo '</div>';
echo '</div>';
echo '</nav>';
echo '</nav>';
echo '<!-- navigation area ending -->';
echo '<main class="main">';
echo '<section class="calculator ">';
echo '<!-- its the heading section -->';
echo '';
echo '<div class="title-holder">';
echo '<h2 class="title">Brick slips and Corner Brick slips calculator';
echo '</h2>';
echo '</div>';
echo '';
echo '<div class="row g-0 ">';
echo '<!-- result area md-100 lg-40  has overlay ,title-sub,box of options and two buttons-->';
echo '<div id="result-card" class="col-md-12 col-lg-5 cn  d-flex justify-content-center align-items-center">';
echo '';
echo '<div class="result__area  text-black bg-white ">';
echo '<h2 class="sub-title mt-4 mb-5">Results</h2>';
echo '<div class="result__toogle1">';
echo '<div class="result__sheet d-flex justify-content-between ">';
echo '<p>Total Sq metres (rounded up)</p>';
echo '<p class="metre">20</p>';
echo '</div>';
echo '<div class="result__sheet d-flex justify-content-between ">';
echo '<p>Number Of Brick Slips</p>';
echo '<p class="number">20</p>';
echo '</div>';
echo '<div class="result__sheet d-flex justify-content-between ">';
echo '<p>Total Boxes</p>';
echo '<p class="boxes">20</p>';
echo '</div>';
echo '<div class="result__buttons d-flex gap-3 justify-content-between mt-5">';
echo '<a href="#to-calcu" class="close__button px-md-4  btn rounded-pill text-white">✖️';
echo 'Close</a>';
echo '<button class="buy__button px-md-4 btn rounded-pill">🛒 Buy now</button>';
echo '</div>';
echo '</div>';
echo '<div class="result__toggle2 ">';
echo '<div class="result__sheet d-flex justify-content-between ">';
echo '<p>Total height (rounded up)</p>';
echo '<p class="metre2">20</p>';
echo '</div>';
echo '<div class="result__sheet d-flex justify-content-between ">';
echo '<p>Total corner packs required</p>';
echo '<p class="number2">20</p>';
echo '</div>';
echo '<div class="result__buttons mt-5 d-flex gap-3 justify-content-between mt-3">';
echo '<a href="#to-calcu" class="close__button  px-md-4 btn rounded-pill text-white">✖️';
echo 'Close</a>';
echo '<button class="buy__button px-md-4 btn rounded-pill">🛒 Buy now</button>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '';
echo '';
echo '</div>';
echo '<!-- calculator area  contain two input ,checkbox ,submit-->';
echo '<div class="col-md-12 col-lg-7 d-flex justify-content-center ">';
echo '<div id="to-calcu" class="calculator__main  gap-3  d-flex pt-5 px-md-4 px-2 flex-column ">';
echo '<div class="toogle-area">';
echo '<div class=" tooglebtn toogle-bg1"></div>';
echo '';
echo '<div id="brick-slip" class="brick-model model1 ">Brick Slips</div>';
echo '<div id="brick-round" class="brick-model model2"> Brick Slip Corners</div>';
echo '</div>';
echo '<form action="#result-card">';
echo '<div class="toggle__modelone togglemodel ">';
echo '<div class="input-area text-white mt-2">';
echo '<p class="small__para mt-3 mb-2"><span>*</span> Enter the height and width in meters';
echo '</p>';
echo '<div class="d-flex justify-content-between pt-0 input-area1">';
echo '<input type="number" required id="width" min="0.1" step="0.01" value="null"';
echo 'placeholder="Enter the width">';
echo '<input type="number" required id="height" min="0.1" step="0.01" value="null"';
echo 'placeholder="Enter the height">';
echo '</div>';
echo '<div class="input-area2 mt-4">';
echo '<div class="form-check form-switch">';
echo '<input class="form-check-input" id="check1" value="" type="checkbox"';
echo 'id="flexSwitchCheckChecked" checked>';
echo '<label class="form-check-label" for="flexSwitchCheckChecked">10% For Cuts';
echo 'and';
echo 'Wastages</label>';
echo '</div>';
echo '<div class="form-check form-switch">';
echo '<input class="form-check-input d-none" id="check2" step="0.01"';
echo 'type="checkbox" id="flexSwitchCheckChecked" checked>';
echo '<label class="form-check-label d-none" for="flexSwitchCheckChecked">Piller';
echo 'pierce</label>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="submit-button  text-center mt-4 mb-3">';
echo '<button class="submit" class=" ">Submit</button>';
echo '</div>';
echo '<div class="additional__data text-white">';
echo '<p>';
echo 'What will I need? <br>';
echo 'Brickslips <br>';
echo 'Adhesive <br>';
echo 'Mortar <br>';
echo 'Notched Adhesive Trowel <br>';
echo 'Mixing bucket <br>';
echo 'Spirit level <br>';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</form>';
echo '<div class="tooglemodel2 hidden-toggle">';
echo '<p class="small__para mt-3 mb-2 text-white"><span>*</span>Enter the height of your corner in';
echo '<br> meters to calculate corner packs required';
echo '</p>';
echo '<!-- <div class="ffffff"> -->';
echo '<form action="#result-card">';
echo '<div class="d-flex mb-5  justify-content-between pt-0 input-area1">';
echo '<input type="number" id="height2" required value="null" min="0.1" step="0.01"';
echo 'placeholder="Enter the height">';
echo '</div>';
echo '<div class="submit-button mt-5 mb-3">';
echo '<button class="submit" class=" ">Submit</button>';
echo '</div>';
echo '</form>';
echo '<!-- </div> -->';
echo '';
echo '<p class="small__para mt-4 mb-3 text-white"><span>*</span> corner pack contains 7 corners';
echo '</p>';
echo '<div class="additional__data text-white">';
echo '<p>';
echo 'What will I need? <br>';
echo 'Brickslips <br>';
echo 'Adhesive <br>';
echo 'Mortar <br>';
echo 'Notched Adhesive Trowel <br>';
echo 'Mixing bucket <br>';
echo 'Spirit level <br>';
echo '</p>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<!-- <input type="text" id="width">';
echo '<input type="text" id="height"> -->';
echo '';
echo '';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '';
echo '</section>';
echo '<!-- new section accordion staring -->';
echo '<section class="accordian__area   mt-5">';
echo '<div class="col-md-8 col-12  my-5 py-5 mx-auto">';
echo '<h1 class="px-3 faq mb-4">FAQ</h1>';
echo '<!-- Attribution -->';
echo '';
echo '<div class="accordion accordion-flush" id="accordionFlushExample">';
echo '<div class="accordion-item">';
echo '<h2 class="accordion-header" id="flush-headingOne">';
echo '<button class="accordion-button collapsed " type="button" data-bs-toggle="collapse"';
echo 'data-bs-target="#flush-collapseOne" aria-expanded="false"';
echo 'aria-controls="flush-collapseOne">';
echo 'HOW MANY BRICK SLIPS DO I NEED?';
echo '</button>';
echo '</h2>';
echo '<div id="flush-collapseOne" class="accordion-collapse collapse"';
echo 'aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">';
echo '<div class="accordion-body">To calculate the number of brick slips you require, you must';
echo 'first calculate the size off the area you are wanting to';
echo 'cover, this is done by using the below formula;';
echo '';
echo 'Length of wall (in meters) x Height of wall (in meters) = Total area in Square meters';
echo '';
echo 'You have decided to add a feature wall in your kitchen above your worktops, the Length';
echo 'of the wall is 4.5 meters, and';
echo 'you would like it 0.6meters high;';
echo '';
echo '4.5 x 0.6 = 2.7 square meters .';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="accordion-item">';
echo '<h2 class="accordion-header" id="flush-headingTwo">';
echo '<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"';
echo 'data-bs-target="#flush-collapseTwo" aria-expanded="false"';
echo 'aria-controls="flush-collapseTwo">';
echo 'What Are Brick Slips?';
echo '</button>';
echo '</h2>';
echo '<div id="flush-collapseTwo" class="accordion-collapse collapse"';
echo 'aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">';
echo '<div class="accordion-body">Often referred to as brick tiles, brick slip tiles or brick';
echo 'veneers, brick slips are made from thin cuts of brick,';
echo 'purpose made for various applications. They are mainly used to mimic the look of a';
echo 'traditional brick wall and they are';
echo 'suitable for interior and exterior walls. Pre-cast brick slips are made from concrete or';
echo 'composite material and are';
echo 'moulded and designed to look and feel like real bricks.<br>';
echo '';
echo '<br>';
echo 'In recent years, the demand for traditional brick slips has been increasing and there is';
echo 'a wide variety of options';
echo 'available to cater for any home owner’s preference.';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="accordion-item">';
echo '<h2 class="accordion-header" id="flush-headingfour">';
echo '<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"';
echo 'data-bs-target="#flush-collapsefour" aria-expanded="false"';
echo 'aria-controls="flush-collapsefour">';
echo 'What Are Brick Slips or Brick Slip Tiles Used For?';
echo '</button>';
echo '</h2>';
echo '<div id="flush-collapsefour" class="accordion-collapse collapse"';
echo 'aria-labelledby="flush-headingfour" data-bs-parent="#accordionFlushExample">';
echo '<div class="accordion-body">Brick slips can be used in many areas in the home; you can use';
echo 'them in your bedroom to create a natural, relaxing';
echo 'environment that is suited to your individual style. You can also use them in your';
echo 'bathroom, and choose from a variety';
echo 'of materials that can allow for anything from a minimalist style to a unique modern';
echo 'setting.';
echo '<br>';
echo '<br>';
echo 'Brick slips have a unique style and they are popular to use in both residential and';
echo 'commercial buildings, and even in';
echo 'retail settings. These brick slips create a unique feel and can fit in with almost any';
echo 'theme you want to use throughout';
echo 'your space. Brick slips can be installed almost anywhere, to create a more rustic look,';
echo 'especially since modern homes';
echo 'today are built with a rough facing brick on the outside. This gives home owners the';
echo 'perfect solution to create that';
echo 'popular rustic look.';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="accordion-item">';
echo '<h2 class="accordion-header" id="flush-headingThree">';
echo '<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"';
echo 'data-bs-target="#flush-collapseThree" aria-expanded="false"';
echo 'aria-controls="flush-collapseThree">';
echo 'Why Choose <strong>&nbsp; MY Brick Wall &nbsp;</strong> Company?';
echo '</button>';
echo '</h2>';
echo '<div id="flush-collapseThree" class="accordion-collapse collapse"';
echo 'aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">';
echo '<div class="accordion-body">If you want to use only the best and most reliable brick slips,';
echo 'then BBA approved brick slips are the best option. This';
echo 'is especially important if you want to use brick slips in specific areas in and around';
echo 'the home, where safety and';
echo 'durability is important. This is a good choice if you want to use brick slips in an area';
echo 'where there is more heat.';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</section>';
echo '';
echo '<!-- b faq -->';
echo '';
echo '<!-- b faq -->';
echo '</main>';
echo '';
echo '<!-- javascript area starting -->';
echo '<script src="script.js"></script>';
echo '<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"';
echo 'integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"';
echo 'crossorigin="anonymous"></script>';
echo '<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"';
echo 'integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"';
echo 'crossorigin="anonymous"></script>';
echo '';
echo '</body>';
echo '';
echo '</html>';
echo '';
?>